title: Neha Ravuri's Blog
author: nravuri
email: ravurineha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My final website project!

# social links
twitter_username: NehaRavuri # DO NOT include the @ character, or else the build will fail!
github_username:  nravuri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
